export type CategoryPackage = {
  slug: string
  name: string
  price: number
  image: string
  description: string
  features: string[]
  details: string
  duration: string
  bestFor: string
}

export type DecorCategory = {
  slug: string
  name: string
  shortName: string
  description: string
  heroImage: string
  accent: string
  packages: CategoryPackage[]
}

const birthdayPackages: CategoryPackage[] = [
  {
    slug: 'basic-birthday-package',
    name: 'Basic Birthday Package',
    price: 4999,
    image: 'https://images.unsplash.com/photo-1530103862676-de8c9debad1d?w=900&h=650&fit=crop&q=85',
    description: 'A simple & budget-friendly setup perfect for intimate celebrations.',
    features: ['Balloon Decor', 'Happy Birthday Backdrop', 'Cake Table Setup', 'Basic Party Lights'],
    details: 'A simple and budget-friendly birthday package with balloon decor, backdrop, and party lights for intimate celebrations.',
    duration: '2-3 hours setup',
    bestFor: 'Intimate birthdays',
  },
  {
    slug: 'premium-birthday-package',
    name: 'Premium Birthday Package',
    price: 12999,
    image: 'https://images.unsplash.com/photo-1527529482837-4698179dc6ce?w=900&h=650&fit=crop&q=85',
    description: 'A premium setup with elegant decor and personalized touches.',
    features: ['Premium Balloon Decor', 'Theme Cake Table', 'LED Neon Sign', 'Custom Table Styling', 'Fairy Light Curtains'],
    details: 'A premium birthday package with elegant balloon styling, cake table decor, neon signage, and personalized touches.',
    duration: '3-4 hours setup',
    bestFor: 'Premium birthdays',
  },
  {
    slug: 'luxury-birthday-package',
    name: 'Luxury Birthday Package',
    price: 19999,
    image: 'https://images.unsplash.com/photo-1511795409834-ef04bbd61622?w=900&h=650&fit=crop&q=85',
    description: 'An extravagant setup with luxurious decor and premium add-ons.',
    features: ['Themed Backdrop', 'Customized Props', 'Balloon Installations', 'Entry Decor', 'Premium Lighting'],
    details: 'An extravagant birthday setup with luxury stage styling, customized props, entry decor, and premium lighting.',
    duration: '5-6 hours setup',
    bestFor: 'Luxury parties',
  },
  {
    slug: 'themed-birthday-package',
    name: 'Themed Birthday Package',
    price: 9999,
    image: 'https://images.unsplash.com/photo-1507504031003-b417219a0fde?w=900&h=650&fit=crop&q=85',
    description: 'Custom birthday setups based on your favorite themes and colors.',
    features: ['Theme-Based Decor', 'Personalized Props', 'Cake & Dessert Table', 'Themed Entry Setup', 'Ambient Lighting'],
    details: 'A custom birthday setup designed around your favorite theme, colors, props, and guest experience.',
    duration: '4-5 hours setup',
    bestFor: 'Theme parties',
  },
  {
    slug: 'kids-birthday-package',
    name: 'Kids Birthday Package',
    price: 6999,
    image: 'https://images.unsplash.com/photo-1504196606672-aef5c9cefc92?w=900&h=650&fit=crop&q=85',
    description: "Fun, playful & colorful decor perfect for kids' birthday celebrations.",
    features: ['Cartoon/Theme Backdrop', 'Balloon Decor', 'Kids Table Setup', 'Return Gifts Table', 'Fun Props & Cutouts'],
    details: 'A playful kids birthday package with cartoon themes, colorful balloons, themed props, and child-friendly decor zones.',
    duration: '5-7 hours setup',
    bestFor: 'Kids parties',
  },
  {
    slug: 'elite-birthday-package',
    name: 'Elite Birthday Package',
    price: 24999,
    image: 'https://images.unsplash.com/photo-1519225421980-715cb0215aed?w=900&h=650&fit=crop&q=85',
    description: 'The ultimate birthday experience with grand decor and exclusive features.',
    features: ['Grand Theme Decor', 'Custom Entrance', 'Premium Floral Arrangements', 'Stage & Seating Setup', 'Professional Lighting'],
    details: 'A grand birthday package with premium floral work, custom entrance, stage seating, and exclusive luxury styling.',
    duration: '7-8 hours setup',
    bestFor: 'Elite birthdays',
  },
]

export const decorCategories: DecorCategory[] = [
  {
    slug: 'wedding-decoration',
    name: 'Wedding Decoration',
    shortName: 'Wedding',
    description: 'Mandaps, floral aisles, reception stages, and elegant wedding styling.',
    heroImage: 'https://images.unsplash.com/photo-1519741497674-611481863552?w=1200&h=700&fit=crop&q=85',
    accent: 'from-[#c9386b] to-[#c9932a]',
    packages: [
      {
        slug: 'classic-wedding-stage',
        name: 'Classic Wedding Stage',
        price: 25000,
        image: 'https://images.unsplash.com/photo-1519225421980-715cb0215aed?w=900&h=650&fit=crop&q=85',
        description: 'A refined wedding stage with drapes, florals, and warm lighting.',
        features: ['Stage backdrop', 'Artificial floral work', 'Sofa seating', 'Warm LED lighting'],
        details: 'A graceful setup for ceremonies and receptions that need a timeless wedding backdrop.',
        duration: '8-10 hours setup',
        bestFor: 'Wedding stages',
      },
      {
        slug: 'premium-floral-mandap',
        name: 'Premium Floral Mandap',
        price: 45000,
        image: 'https://images.unsplash.com/photo-1464366400600-7168b8af9bc3?w=900&h=650&fit=crop&q=85',
        description: 'A flower-forward mandap design with aisle and entrance styling.',
        features: ['Mandap structure', 'Fresh floral accents', 'Aisle decor', 'Entry arch'],
        details: 'Designed for couples who want a premium ceremony focal point with elegant flower work.',
        duration: '10-12 hours setup',
        bestFor: 'Wedding ceremonies',
      },
      {
        slug: 'royal-reception-decor',
        name: 'Royal Reception Decor',
        price: 65000,
        image: 'https://images.unsplash.com/photo-1523438885200-e635ba2c371e?w=900&h=650&fit=crop&q=85',
        description: 'A grand reception setup with luxe stage, lighting, and guest photo zones.',
        features: ['Grand stage design', 'Chandelier lighting', 'Photo booth', 'VIP seating decor'],
        details: 'A high-impact package for reception nights, hotel banquets, and premium venues.',
        duration: '12-14 hours setup',
        bestFor: 'Reception events',
      },
    ],
  },
  {
    slug: 'birthday-decoration',
    name: 'Birthday Decoration',
    shortName: 'Birthday',
    description: 'Colorful birthday backdrops, balloon styling, theme props, and party zones.',
    heroImage: 'https://images.unsplash.com/photo-1527529482837-4698179dc6ce?w=1200&h=700&fit=crop&q=85',
    accent: 'from-[#ff4d8d] to-[#ff9f43]',
    packages: birthdayPackages,
  },
  {
    slug: 'anniversary-decoration',
    name: 'Anniversary Decoration',
    shortName: 'Anniversary',
    description: 'Romantic candlelight setups, floral backdrops, and couple celebration decor.',
    heroImage: 'https://images.unsplash.com/photo-1519671482749-fd09be7ccebf?w=1200&h=700&fit=crop&q=85',
    accent: 'from-[#ef476f] to-[#7c3aed]',
    packages: [
      {
        slug: 'romantic-candlelight-setup',
        name: 'Romantic Candlelight Setup',
        price: 7000,
        image: 'https://images.unsplash.com/photo-1535016066981-2e2e3b822dd0?w=900&h=650&fit=crop&q=85',
        description: 'An intimate setup with candles, petals, lights, and couple seating.',
        features: ['Candle decor', 'Rose petals', 'Couple table', 'Fairy lights'],
        details: 'Made for cozy home, terrace, and restaurant anniversary surprises.',
        duration: '3-4 hours setup',
        bestFor: 'Private dinners',
      },
      {
        slug: 'premium-anniversary-backdrop',
        name: 'Premium Anniversary Backdrop',
        price: 12000,
        image: 'https://images.unsplash.com/photo-1515295285027-555fcf8ec0ea?w=900&h=650&fit=crop&q=85',
        description: 'A premium backdrop with floral details and personalized couple elements.',
        features: ['Personalized backdrop', 'Floral frame', 'LED name sign', 'Photo corner'],
        details: 'A polished setup for family anniversary parties and memorable couple photos.',
        duration: '4-5 hours setup',
        bestFor: 'Family celebrations',
      },
      {
        slug: 'luxury-anniversary-suite',
        name: 'Luxury Anniversary Suite',
        price: 18000,
        image: 'https://images.unsplash.com/photo-1507504031003-b417219a0fde?w=900&h=650&fit=crop&q=85',
        description: 'A luxury room or suite decor package with florals, lights, and dining accents.',
        features: ['Room styling', 'Fresh roses', 'Balloon ceiling', 'Dining table decor'],
        details: 'Ideal for hotel suite surprises and premium private anniversary experiences.',
        duration: '5-6 hours setup',
        bestFor: 'Hotel surprises',
      },
    ],
  },
  {
    slug: 'baby-shower-decoration',
    name: 'Baby Shower Decoration',
    shortName: 'Baby Shower',
    description: 'Soft pastel baby shower setups with cozy backdrops and elegant props.',
    heroImage: 'https://images.unsplash.com/photo-1504196606672-aef5c9cefc92?w=1200&h=700&fit=crop&q=85',
    accent: 'from-[#38bdf8] to-[#f9a8d4]',
    packages: [
      {
        slug: 'pastel-baby-shower',
        name: 'Pastel Baby Shower Decor',
        price: 9000,
        image: 'https://images.unsplash.com/photo-1504196606672-aef5c9cefc92?w=900&h=650&fit=crop&q=85',
        description: 'A gentle pastel setup with balloons, florals, and mom-to-be seating.',
        features: ['Pastel balloon arch', 'Mom-to-be chair', 'Baby blocks', 'Cake table'],
        details: 'A sweet, soft look for home baby showers and close family gatherings.',
        duration: '4-5 hours setup',
        bestFor: 'Home baby showers',
      },
      {
        slug: 'gender-reveal-decor',
        name: 'Gender Reveal Decor',
        price: 14000,
        image: 'https://images.unsplash.com/photo-1478146896981-b80fe463b330?w=900&h=650&fit=crop&q=85',
        description: 'A blue-and-pink reveal setup with reveal moment styling.',
        features: ['Reveal backdrop', 'Balloon wall', 'Confetti zone', 'Photo props'],
        details: 'Built for an exciting reveal moment with balanced decor and photo-friendly styling.',
        duration: '5-6 hours setup',
        bestFor: 'Gender reveals',
      },
      {
        slug: 'luxury-baby-welcome',
        name: 'Luxury Baby Welcome',
        price: 22000,
        image: 'https://images.unsplash.com/photo-1519689680058-324335c77eba?w=900&h=650&fit=crop&q=85',
        description: 'A premium welcome setup with florals, lights, and custom signage.',
        features: ['Custom signage', 'Premium florals', 'Soft lighting', 'Welcome arch'],
        details: 'A luxury decor package for baby arrival celebrations and premium venue styling.',
        duration: '6-7 hours setup',
        bestFor: 'Baby welcome events',
      },
    ],
  },
  {
    slug: 'engagement-decoration',
    name: 'Engagement Decoration',
    shortName: 'Engagement',
    description: 'Ring ceremony backdrops, floral stages, couple seating, and photo spots.',
    heroImage: 'https://images.unsplash.com/photo-1511285560929-80b456fea0bc?w=1200&h=700&fit=crop&q=85',
    accent: 'from-[#a855f7] to-[#ec4899]',
    packages: [
      {
        slug: 'ring-ceremony-stage',
        name: 'Ring Ceremony Stage',
        price: 18000,
        image: 'https://images.unsplash.com/photo-1511285560929-80b456fea0bc?w=900&h=650&fit=crop&q=85',
        description: 'A graceful engagement stage with couple seating and floral highlights.',
        features: ['Ring stage backdrop', 'Couple sofa', 'Floral side panels', 'Warm lighting'],
        details: 'Perfect for intimate ring ceremonies and elegant family events.',
        duration: '6-7 hours setup',
        bestFor: 'Ring ceremonies',
      },
      {
        slug: 'premium-engagement-florals',
        name: 'Premium Engagement Florals',
        price: 30000,
        image: 'https://images.unsplash.com/photo-1519225421980-715cb0215aed?w=900&h=650&fit=crop&q=85',
        description: 'A premium floral stage design with personalized initials and photo zone.',
        features: ['Fresh floral look', 'Initials signage', 'Photo booth', 'Entry styling'],
        details: 'A romantic and premium decor package for stylish engagement evenings.',
        duration: '7-8 hours setup',
        bestFor: 'Premium engagements',
      },
      {
        slug: 'luxury-engagement-evening',
        name: 'Luxury Engagement Evening',
        price: 48000,
        image: 'https://images.unsplash.com/photo-1523438885200-e635ba2c371e?w=900&h=650&fit=crop&q=85',
        description: 'A grand engagement setup with luxe stage, ceiling lights, and guest zones.',
        features: ['Luxury stage', 'Ceiling lights', 'Guest photo area', 'VIP table decor'],
        details: 'A complete decor concept for larger engagement functions and banquet venues.',
        duration: '9-10 hours setup',
        bestFor: 'Banquet functions',
      },
    ],
  },
  {
    slug: 'corporate-event-decoration',
    name: 'Corporate Event Decoration',
    shortName: 'Corporate',
    description: 'Brand-aligned decor for conferences, launches, awards, and office events.',
    heroImage: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=1200&h=700&fit=crop&q=85',
    accent: 'from-[#2563eb] to-[#14b8a6]',
    packages: [
      {
        slug: 'conference-stage-setup',
        name: 'Conference Stage Setup',
        price: 20000,
        image: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=900&h=650&fit=crop&q=85',
        description: 'A clean, professional stage setup for meetings and conferences.',
        features: ['Stage backdrop', 'Podium decor', 'Brand colors', 'Basic lighting'],
        details: 'A sharp corporate package for seminars, conferences, and internal events.',
        duration: '5-6 hours setup',
        bestFor: 'Conferences',
      },
      {
        slug: 'product-launch-decor',
        name: 'Product Launch Decor',
        price: 35000,
        image: 'https://images.unsplash.com/photo-1511578314322-379afb476865?w=900&h=650&fit=crop&q=85',
        description: 'A brand-led launch setup with product display and media photo zone.',
        features: ['Launch backdrop', 'Product pedestal', 'Media wall', 'Accent lighting'],
        details: 'Built for product reveals, brand activations, and press-friendly launches.',
        duration: '7-8 hours setup',
        bestFor: 'Brand launches',
      },
      {
        slug: 'corporate-awards-night',
        name: 'Corporate Awards Night',
        price: 55000,
        image: 'https://images.unsplash.com/photo-1505373877841-8d25f7d46678?w=900&h=650&fit=crop&q=85',
        description: 'A premium awards setup with stage lighting, branding, and VIP styling.',
        features: ['Awards stage', 'LED-style backdrop', 'Trophy display', 'VIP decor'],
        details: 'A premium package for annual awards, gala nights, and recognition events.',
        duration: '8-10 hours setup',
        bestFor: 'Award nights',
      },
    ],
  },
  {
    slug: 'house-warming-decoration',
    name: 'House Warming Decoration',
    shortName: 'House Warming',
    description: 'Welcoming entrance, floral, pooja, and home celebration decoration.',
    heroImage: 'https://images.unsplash.com/photo-1467883453080-8ac3256e75a0?w=1200&h=700&fit=crop&q=85',
    accent: 'from-[#f59e0b] to-[#22c55e]',
    packages: [
      {
        slug: 'traditional-house-warming',
        name: 'Traditional House Warming',
        price: 8000,
        image: 'https://images.unsplash.com/photo-1533900298318-6b8da08a523e?w=900&h=650&fit=crop&q=85',
        description: 'Traditional floral entrance and pooja area styling for a new home.',
        features: ['Door toran', 'Pooja backdrop', 'Marigold strings', 'Rangoli corner'],
        details: 'A warm and traditional setup for griha pravesh and family rituals.',
        duration: '3-4 hours setup',
        bestFor: 'Griha pravesh',
      },
      {
        slug: 'premium-home-entry-decor',
        name: 'Premium Home Entry Decor',
        price: 15000,
        image: 'https://images.unsplash.com/photo-1516739313521-c79898d51c64?w=900&h=650&fit=crop&q=85',
        description: 'A premium entrance and living area decor package for house warming.',
        features: ['Entrance arch', 'Floral console', 'Fairy lights', 'Welcome signage'],
        details: 'Designed to make the first impression of your new home feel inviting and festive.',
        duration: '4-5 hours setup',
        bestFor: 'Home welcomes',
      },
      {
        slug: 'luxury-house-warming-party',
        name: 'Luxury House Warming Party',
        price: 26000,
        image: 'https://images.unsplash.com/photo-1511795409834-ef04bbd61622?w=900&h=650&fit=crop&q=85',
        description: 'A stylish home party decor setup with lighting, florals, and guest zones.',
        features: ['Living room styling', 'Guest photo wall', 'Premium florals', 'Ambient lights'],
        details: 'A modern house warming package for evening parties and premium home gatherings.',
        duration: '6-7 hours setup',
        bestFor: 'House parties',
      },
    ],
  },
  {
    slug: 'farewell-decoration',
    name: 'Farewell Decoration',
    shortName: 'Farewell',
    description: 'Farewell stages, memory walls, photo corners, and celebration decor.',
    heroImage: 'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=1200&h=700&fit=crop&q=85',
    accent: 'from-[#111827] to-[#ff4d8d]',
    packages: [
      {
        slug: 'school-farewell-decor',
        name: 'School Farewell Decor',
        price: 10000,
        image: 'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=900&h=650&fit=crop&q=85',
        description: 'A lively farewell setup for school stages and student photo corners.',
        features: ['Stage backdrop', 'Balloon columns', 'Memory wall', 'Photo props'],
        details: 'A colorful package for student farewells, classroom parties, and stage events.',
        duration: '4-5 hours setup',
        bestFor: 'School farewells',
      },
      {
        slug: 'college-farewell-theme',
        name: 'College Farewell Theme',
        price: 18000,
        image: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=900&h=650&fit=crop&q=85',
        description: 'A theme-based farewell decor package with stage and party lighting.',
        features: ['Theme stage', 'LED lights', 'Entry decor', 'Photo booth'],
        details: 'A stylish setup for college farewell nights, freshers-farewell events, and socials.',
        duration: '5-7 hours setup',
        bestFor: 'College events',
      },
      {
        slug: 'corporate-farewell-evening',
        name: 'Corporate Farewell Evening',
        price: 28000,
        image: 'https://images.unsplash.com/photo-1511578314322-379afb476865?w=900&h=650&fit=crop&q=85',
        description: 'A premium farewell evening decor setup for offices and professional teams.',
        features: ['Corporate backdrop', 'Memory display', 'Stage lighting', 'Table styling'],
        details: 'A professional yet warm package for retirement parties and team farewell evenings.',
        duration: '6-8 hours setup',
        bestFor: 'Office farewells',
      },
    ],
  },
]

export function getDecorCategory(slug: string) {
  return decorCategories.find((category) => category.slug === slug)
}

export function getCategoryPackage(categorySlug: string, packageSlug: string) {
  const category = getDecorCategory(categorySlug)
  return category?.packages.find((item) => item.slug === packageSlug)
}
